"""rename bug pattern to knowledge entry

Revision ID: 5a1d7d7485ac
Revises: 81414023d8d4
Create Date: 2026-08-01 18:23:23.609224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a1d7d7485ac'
down_revision: Union[str, Sequence[str], None] = '81414023d8d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('common_fix', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_error_type'), 'knowledge_entries', ['error_type'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_id'), 'knowledge_entries', ['id'], unique=False)
    op.add_column('analyses', sa.Column('knowledge_entry_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('analyses_bug_report_id_fkey'), 'analyses', type_='foreignkey')
    op.create_foreign_key(None, 'analyses', 'knowledge_entries', ['knowledge_entry_id'], ['id'])
    op.drop_column('analyses', 'bug_report_id')
    op.drop_index(op.f('ix_bug_reports_id'), table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('bug_report_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'analyses', type_='foreignkey')
    op.create_foreign_key(op.f('analyses_bug_report_id_fkey'), 'analyses', 'bug_reports', ['bug_report_id'], ['id'])
    op.drop_column('analyses', 'knowledge_entry_id')
    op.create_table('bug_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('framework', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stack_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_bug_reports_project_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bug_reports_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bug_reports_pkey'))
    )
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_knowledge_entries_id'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_error_type'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
