"""add bug knowledge base table

Revision ID: 7a45690ba414
Revises: a7c9eed6980f
Create Date: 2026-07-22 11:13:38.619377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a45690ba414'
down_revision: Union[str, Sequence[str], None] = 'a7c9eed6980f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('framework', sa.String(), nullable=False),
    sa.Column('error_pattern', sa.String(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_knowledge_base_id'), 'bug_knowledge_base', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_knowledge_base_id'), table_name='bug_knowledge_base')
    op.drop_table('bug_knowledge_base')
    # ### end Alembic commands ###
