"""add project_id to bug_reports

Revision ID: 81414023d8d4
Revises: db561d3cc486
Create Date: 2026-07-31 20:02:08.527120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81414023d8d4'
down_revision: Union[str, Sequence[str], None] = 'db561d3cc486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # create project_id column
    op.add_column(
        'bug_reports',
        sa.Column('project_id', sa.Integer(), nullable=True)
    )

    # create default user first
    op.execute("""
        INSERT INTO users (id, email, hashed_password)
        SELECT 1, 'system@traceai.com', 'disabled'
        WHERE NOT EXISTS (
            SELECT 1 FROM users WHERE id = 1
        )
    """)

    # create default project after user exists
    op.execute("""
        INSERT INTO projects (id, name, owner_id)
        SELECT 1, 'Default Project', 1
        WHERE NOT EXISTS (
            SELECT 1 FROM projects WHERE id = 1
        )
    """)

    # assign existing bug reports to default project
    op.execute("""
        UPDATE bug_reports
        SET project_id = 1
        WHERE project_id IS NULL
    """)

    # make project_id required
    op.alter_column(
        'bug_reports',
        'project_id',
        nullable=False
    )

    # add foreign key
    op.create_foreign_key(
        'fk_bug_reports_project_id',
        'bug_reports',
        'projects',
        ['project_id'],
        ['id']
    )   # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bug_reports', type_='foreignkey')
    op.create_index(op.f('ix_bug_reports_id'), 'bug_reports', ['id'], unique=False)
    op.drop_column('bug_reports', 'project_id')
    # ### end Alembic commands ###
