"""add bug pattern knowledge base

Revision ID: a7c9eed6980f
Revises: f1f8c16719f7
Create Date: 2026-07-21 16:38:49.232802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c9eed6980f'
down_revision: Union[str, Sequence[str], None] = 'f1f8c16719f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=100), nullable=True),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('common_fix', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bug_patterns_error_type'), 'bug_patterns', ['error_type'], unique=False)
    op.create_index(op.f('ix_bug_patterns_id'), 'bug_patterns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bug_patterns_id'), table_name='bug_patterns')
    op.drop_index(op.f('ix_bug_patterns_error_type'), table_name='bug_patterns')
    op.drop_table('bug_patterns')
    # ### end Alembic commands ###
